echo "hello world"
echo "adding a new line as part of version 1"
echo "adding a new line as part of test image"
echo "test for existing version"
echo "changes done in version file to get the correct latest version"
echo "changes done in version file to check if any git commits are pending"
echo "changes done in version file to check if any git commits are pending - 2"
